### ISSUE TITLE
Could u tell how to get the dataset

### ISSUE THREAD

**Issue by wjj31767** [lemonwaffle/detectron2-1#1]
Hi,

I'm new to detectron2, but very interested in DAG. But I can't figure out how did u get the dataset, or can I get a relative smaller dataset for just run the DAG and see the result?

Best 
Jingjian

**Comment by yizhe-ang** [comment]
Hi Jingjian,

You can simply grab a model pretrained on the COCO dataset (from detectron2) and run some COCO images on it using DAG. https://cocodataset.org/

PS: my DAG implementation isn't exactly 100% faithful to the paper
