### ISSUE TITLE
Viewing Predictions Code

### ISSUE THREAD

**Issue by PrinceEAdjei** [lemonwaffle/detectron2-1#2]
hi! Great code thanks for the wonderful work. 

I have a problem with the visualization_json_predictions code. For some reason, it shows predictions on a small percentage of the test dataset. The rest of the images in the test dataset do not have any predictions on them.

Is there a bug somewhere? Thanks

**Comment by yizhe-ang** [comment]
According to the code it should perform inference on all samples. Can you adjust the `--conf-threshold` argument to see if there is any difference in predictions?

**Comment by PrinceEAdjei** [comment]
Yes, sure. It works perfectly now. I adjusted the default --conf-threshold argument within the .py code and it works now. Thanks for the quick response!
