### ISSUE TITLE
run_DAG with problem "RuntimeError: CUDA error: device-side assert triggered"

### ISSUE THREAD

**Issue by ghost** [lemonwaffle/detectron2-1#4]
Hi, thanks for the contributions.

I run into the problem "RuntimeError: CUDA error: device-side assert triggered" with run_DAG. It is related with the function "_get_targets" in detector. I used the faster_rcnn config with COCO_2017_val. The visualization of detectron works correctly.

Is there anything wrong with my settings?

**Comment by yizhe-ang** [comment]
Have you run the script with the `CUDA_LAUNCH_BLOCKING=1` flag to get a more accurate stack trace?
